---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"
    bastion:
      ansible_ssh_user: "linux"
      ansible_host: 80.158.4.229
    csm_k8s-master-1:
      ansible_ssh_user: "linux"
      ansible_host: 80.158.49.178
    csm_k8s-node-nf-1:
      ansible_ssh_user: "linux"
      ansible_host: 192.168.0.107
    csm_k8s-node-nf-2:
      ansible_ssh_user: "linux"
      ansible_host: 192.168.0.98
  children:
    kube-node:
      hosts:
        csm_k8s-node-nf-1:
        csm_k8s-node-nf-2:
    kube-master:
      hosts:
        csm_k8s-master-1:
    bastion:
      hosts:
        bastion:
