---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"
    bastion1:
      ansible_ssh_user: "linux"
      ansible_host: 80.158.5.21
    master1:
      ansible_ssh_user: "linux"
      ansible_host: 80.158.19.221
    node1:
      ansible_ssh_user: "linux"
      ansible_host: 192.168.0.120
    node2:
      ansible_ssh_user: "linux"
      ansible_host: 192.168.0.188
  children:
    k8s-cluster:
      children:
        kube-node:
          hosts:
            node1:
            node2:
        kube-master:
          hosts:
            master:
        etcd:
          hosts:
            master:
    bastion:
      hosts:
        bastion:
