---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"
  children:
    k8s-cluster:
      children:
        kube-node:
          hosts:
            node1:
            node2:
        kube-master:
          hosts:
            master1:
        etcd:
          hosts:
            master1:
    bastion:
      hosts:
        bastion1:
    nodes:
      hosts:
        node1:
        node2:
    no-floating:
      hosts:
        master1:
        node1:
        node2:
