kind: Deployment
apiVersion: apps/v1
metadata:
  name: teamcity-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: teamcity-agent
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
       containers:
       - name: teamcityagent
         image: jetbrains/teamcity-agent
         env:
           - name: SERVER_URL
             value: "http://{{ bastion_fips[0] }}"
           - name: DOCKER_IN_DOCKER
             value: start
         securityContext:
           privileged: true
