---
- name: Prepare user
  hosts: kube-master
  become: yes
  tasks:
    - name: prepare cluster config
      shell: |
        sudo cp /etc/kubernetes/admin.conf $HOME/
        sudo chown $(id -u):$(id -g) $HOME/admin.conf
        export KUBECONFIG=$HOME/admin.conf

    - name: Install required packages
      apt:
        name:
          - python3-setuptools
          - python3-pip
          - build-essential
          - python3-dev

    - name: Install openshift
      pip:
        name: openshift

- name: Prepare pods
  hosts: kube-master
  become: yes
  tasks:
    - name: Apply TeamCity Server definition.
      k8s:
        state: present
        definition: "{{ lookup('template', 'files/teamcity/teamcity-server.yml') }}"

    - name: Apply TeamCity service definition.
      k8s:
        state: present
        definition: "{{ lookup('template', 'files/teamcity/teamcity-service.yml') }}"

    - name: Apply TeamCity Agent definition.
      k8s:
        state: present
        definition: "{{ lookup('template', 'files/teamcity/teamcity-agent.yml') }}"

- name: Install nginx reverse proxy to Bastion
  hosts: bastion
  become: yes
  vars:
    nodename: "{{ groups['nodes'][0] }}"
    psql_addr: "{{ db_address.split(':')[0] }}"
    psql_port: "{{ db_address.split(':')[1] }}"
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-setuptools
          - python3-pip
          - libpq-dev
          - build-essential
          - python3-dev

    - name: Install psycopg2
      pip:
        name: psycopg2

    - name: Create a new database with name "teamcity"
      postgresql_db:
        login_user: "{{ db_username }}"
        login_host: "{{ psql_addr }}"
        login_password: "{{ db_password }}"
        port: "{{ psql_port }}"
        name: teamcity
  roles:
    - role: geerlingguy.nginx
      vars:
        nginx_remove_default_vhost: yes
        nginx_vhosts:
          - listen: "80"
            server_name: "localhost"
            extra_parameters: |
              location / {
                  proxy_pass http://{{ hostvars.node1.ansible_host }}:31600;
                  proxy_set_header Host $host;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_http_version 1.1;
              }
