---
- name: Prepare host
  hosts: kube-master
  become: yes
  tasks:
    - name: Retrieve kubectl config file from the master server.
      fetch:
        src: /root/.kube/config
        dest: files/kubectl-config
        flat: yes